/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * These values define various methods of following a subject
 */
public class FOLLOW_MODE {
   public static final int MOTION_FOLLOW = 0; /* Platform moves in whatever method it can to best follow a subject using subject_follow_dist and subject_follow_bearing as suggestions | */
   public static final int FIXED_FOLLOW = 1; /* Platform maintains a fixed range (subject_follow_dist) and bearing (subject_follow_bearing) to the subject | */
   public static final int ORBIT = 2; /* Platform continually orbits the moving subject at subject_follow_dist radius. Ignores subject_follow_bearing | */
   public static final int TRIPOD = 3; /* Platform stays stationary but its sensors follow the subject.  Ignores subject_follow_dist and subject_follow_bearing | */
   public static final int FOLLOW_MODE_ENUM_END = 4; /*  | */
}
            