/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * Exploration status flags, sent as part of the EXPLORATION_STATUS message.
 */
public class MAV_EXPLORATION_STATUS_FLAGS {
   public static final int MAV_EXPLORATION_STATUS_FLAGS_EXPLORATION_DISABLED = 1; /* Exploration capability disabled. | */
   public static final int MAV_EXPLORATION_STATUS_FLAGS_TASK_INACTIVE = 2; /* Exploration task is inactive. | */
   public static final int MAV_EXPLORATION_STATUS_FLAGS_TASK_STOPPED = 4; /* Exploration task is stopped. | */
   public static final int MAV_EXPLORATION_STATUS_FLAGS_TASK_START_INHIBITED = 8; /* Exploration task start is inhibited, caused by a fault or unmet condition. | */
   public static final int MAV_EXPLORATION_STATUS_FLAGS_TASK_TIME_OUT = 16; /* Exploration task timed-out. | */
   public static final int MAV_EXPLORATION_STATUS_FLAGS_TASK_OUT_OF_BOUNDS = 32; /* Vehicle detected to be out of defined exploration boundaries of the exploration task. | */
   public static final int MAV_EXPLORATION_STATUS_FLAGS_VIO_FAULT = 64; /* Exploration task fault caused by a VIO problem. | */
   public static final int MAV_EXPLORATION_STATUS_FLAGS_NAVIGATION_FAULT = 128; /* Exploration task fault caused by a navigation problem. | */
   public static final int MAV_EXPLORATION_STATUS_FLAGS_ENUM_END = 129; /*  | */
}
            