/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * 
        Point-of-Interest classification. Used on the the POI_REPORT 'classification' field. Provides default classes (0 to 2147483647).
      
 */
public class POI_CLASSIFICATION {
   public static final int POI_CLASSIFICATION_UNKNOWN = 0; /* Unknown classification. | */
   public static final int POI_CLASSIFICATION_GEO_MARKER = 1; /* Geolocation marker. | */
   public static final int POI_CLASSIFICATION_LANDING_PAD = 2; /* Landing pad. | */
   public static final int POI_CLASSIFICATION_CLEAR_LANDING_SPOT = 3; /* Detected suited landing spot. | */
   public static final int POI_CLASSIFICATION_BUILDING = 4; /* Generic building (unidentified type). | */
   public static final int POI_CLASSIFICATION_RESIDENTIAL_BUILDING = 5; /* Residential building. Eg. house, cottage, housebarn, tonwhouse, retirement home. | */
   public static final int POI_CLASSIFICATION_COMERCIAL_OFFICE_BUILDING = 6; /* Comercial office building. | */
   public static final int POI_CLASSIFICATION_COMERCIAL_RETAIL_BUILDING = 7; /* Comercial retail building. Eg. shopping center, retail outlet. | */
   public static final int POI_CLASSIFICATION_COMERCIAL_HOTEL_BUILDING = 8; /* Comercial hotel building. Eg. hotel, motel, resort. | */
   public static final int POI_CLASSIFICATION_COMERCIAL_SPECIAL_PURPOSE_BUILDING = 9; /* Comercial special purpose building. Eg. theater, cinema, self-storage, marina. | */
   public static final int POI_CLASSIFICATION_INDUSTRIAL_MANUFACTURING_BUILDING = 10; /* Industrial manufacturing building. | */
   public static final int POI_CLASSIFICATION_INDUSTRIAL_WAREHOUSE_BUILDING = 11; /* Industrial warehouse building. | */
   public static final int POI_CLASSIFICATION_INDUSTRIAL_FLEX_SPACE_BUILDING = 12; /* Industrial flex space building. Eg. data center, showroom, laboratory. | */
   public static final int POI_CLASSIFICATION_AGRICULTURAL_BUILDING = 13; /* Agricultural building. Eg. barn, greenhouse, silo, stable, windmill, chickenhouse. | */
   public static final int POI_CLASSIFICATION_INFRASTRUCTURE_BUILDING = 14; /* Infrastructure building. Eg. dam, power plant, waste transfer cetner, composting facility. | */
   public static final int POI_CLASSIFICATION_INSTITUTIONAL_MEDICAL_BUILDING = 15; /* Institutional medical building. Eg. hospital, nursing home. | */
   public static final int POI_CLASSIFICATION_INSTITUTIONAL_EDUCATIONAL_BUILDING = 16; /* Institutional educational building. Eg. college, school, orphanage. | */
   public static final int POI_CLASSIFICATION_INSTITUTIONAL_CIVIC_BUILDING = 17; /* Institutional civic building. Eg. library, museum, community hall. | */
   public static final int POI_CLASSIFICATION_INSTITUTIONAL_RELIGIOUS_BUILDING = 18; /* Institutional religious building. Eg. church, monastery, synagogue. | */
   public static final int POI_CLASSIFICATION_INSTITUTIONAL_GOVERNMENT_BUILDING = 19; /* Institutional government building. Eg. embassy, police station, fire station, city hall, post office. | */
   public static final int POI_CLASSIFICATION_INSTITUTIONAL_MILITARY_BUILDING = 20; /* Institutional military building. Eg. barracks, arsenal, bunker, citadel. | */
   public static final int POI_CLASSIFICATION_INSTITUTIONAL_TRANSPORTATION_BUILDING = 21; /* Institutional transportation building. Eg. airport, bus station, lighthouse, ferry terminal. | */
   public static final int POI_CLASSIFICATION_BUILDING_DOOR = 22; /* Building door. | */
   public static final int POI_CLASSIFICATION_BUILDING_WINDOW = 23; /* Building window. | */
   public static final int POI_CLASSIFICATION_BUILDING_VENT = 24; /* Building vent. | */
   public static final int POI_CLASSIFICATION_PERSON = 25; /* Person. | */
   public static final int POI_CLASSIFICATION_CIVILIAN_PERSON = 26; /* Civilian person. | */
   public static final int POI_CLASSIFICATION_MILITARY_PERSON = 27; /* Military person. | */
   public static final int POI_CLASSIFICATION_INGRESS_PORTAL = 28; /* Object or structure ingress portal. | */
   public static final int POI_CLASSIFICATION_EGRESS_PORTAL = 29; /* Object or structure egress portal. | */
   public static final int POI_CLASSIFICATION_VEHICLE = 30; /* Vehicle (unidentified type). | */
   public static final int POI_CLASSIFICATION_GROUND_MANNED_VEHICLE = 31; /* Ground manned vehicle. | */
   public static final int POI_CLASSIFICATION_GROUND_UNMANNED_VEHICLE = 32; /* Ground unmanned vehicle. | */
   public static final int POI_CLASSIFICATION_MANNED_AIRCRAFT = 33; /* Manned aircraft. | */
   public static final int POI_CLASSIFICATION_UNMANNED_AIRCRAFT = 34; /* Unmanned aircraft. | */
   public static final int POI_CLASSIFICATION_MANNED_WATERCRAFT = 35; /* Manned watercraft. | */
   public static final int POI_CLASSIFICATION_UNMANNED_WATERCRAFT = 36; /* Unmanned watercraft. | */
   public static final int POI_CLASSIFICATION_MANNED_AMPHIBIOUS_VEHICLE = 37; /* Manned amphibious vehicle. | */
   public static final int POI_CLASSIFICATION_UNMANNED_AMPHIBIOUS_VEHICLE = 38; /* Unmanned amphibious vehicle. | */
   public static final int POI_CLASSIFICATION_RAILED_VEHICLE = 39; /* Land Vehicle. | */
   public static final int POI_CLASSIFICATION_ANIMAL = 40; /* Animal (unidentified species). | */
   public static final int POI_CLASSIFICATION_ENUM_END = 41; /*  | */
}
            