/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * Point-of-Interest geometry types.
 */
public class POI_GEOMETRY_TYPE {
   public static final int POI_GEOMETRY_TYPE_UNKNOWN = 0; /* Unknown geometry. | */
   public static final int POI_GEOMETRY_TYPE_SQUARE = 1; /* Square. | */
   public static final int POI_GEOMETRY_TYPE_RECTANGLE = 2; /* Rectangle. | */
   public static final int POI_GEOMETRY_TYPE_CIRCLE = 3; /* Circle. | */
   public static final int POI_GEOMETRY_TYPE_CUBE = 4; /* Cube. | */
   public static final int POI_GEOMETRY_TYPE_CUBOID = 5; /* Cuboid. | */
   public static final int POI_GEOMETRY_TYPE_SPHERE = 6; /* Sphere. | */
   public static final int POI_GEOMETRY_TYPE_CYLINDER = 7; /* Cylinder. | */
   public static final int POI_GEOMETRY_TYPE_ENUM_END = 8; /*  | */
}
            